name: Docker Image CI

on:
  push:
    branches: [ "aj" ]
  pull_request:
    branches: [ "aj" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Ali Docker
      uses: docker/login-action@v1
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALI_DOCKER_HUB_USN }}
        password: ${{ secrets.ALI_DOCKER_HUB_PWD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/ydlj:suna.work
